# Proposal Outline {-}


## Introduction  {-}  
### Overview of Assessment{-}  
### History of Assessment Literacy and Instruments{-}  
### Approaches to Assessment{-}  
### Assessment in Higher Ed{-}  
### Impact of Technology on Assessment in Higher Ed{-}  
 

## Dissertation Structure {-}

### Overview of Dissertation Papers{-}

- Dissertation papers must be determined by the committee to be _publishable_.   
- At UVic, it is typical that one must be in publication at the time of the oral defense and the other two should have been submitted for publication.  
- The PhD student must be first author on all papers considered for the dissertation, but co-authors are common and can be determined within the committee.  
- While individual journals provide word limits, the papers considered for the dissertation may exceed those limits for assessment purposes, then be revised for publication.  
- There are typically 5 chapters, but more may be determined to be necessary.

### Timeline for dissertation{-}
- first 2 published at same time

## Paper 1 - *Assessment in higher education: A review of the literature* (Madland, Irvine, DeLuca & Bulut)  {-}

**Journal**  

- [Assessment and Evaluation in Higher Education](https://www.tandfonline.com/toc/CAEH20/current)  
    - 7000 words incl. tables, references, captions, footnotes, endnotes  
    - Gold Open Access - $3605USD  

### Defining Assessment.{-}  

### Assessment and Measurement.{-}  

### Assessment Literacy{-}  

### Approaches to Assessment{-}  

### Assessment in Higher Education. {-}  

### Impact of Technology on Assessment in Higher Education {-}  

<!---

- [Assessment in Education: Principles, Policy, & Practice](https://www.tandfonline.com/toc/caie20/current)
    - Gold Open Access - $2885USD


### Timeline {-} 
- Summer 2022
--->

## Paper 2 - *Validating the* Approaches to Classroom Assessment Inventory *in higher education* - (Madland, DeLuca, Bulut & Irvine) {-}
**Journal**  

- [Assessment, Testing and Applied Measurement (Frontiers in Education)](https://www.frontiersin.org/journals/education/sections/assessment-testing-and-applied-measurement#about)  
    - "Free from the restrictions created by print-based page limits, studies in this section need only demonstrate robustness in theory, method, and analysis to be accepted. The significance or importance of a paper will be decided by open-access readership who will hopefully cite and draw on the work in this section."  
    - APC - $950USD  

### History and Development of *ACAI* {-}  

### Overview of research {-}  

### Development of *ACAI* for higher ed {-}  

### Methods {-}  

### Results {-}  

### Discussion {-}  

### Conclusions and Recommendations {-}  

<!---



### Timeline {-}
- Spring 2023
--->

## Paper 3 (Emergent) - *Assessment and technology in higher education* (Madland, Irvine, Bulut, DeLuca) {-} 

**Journal**  

- [OTESSA](https://journal.otessa.org/index.php/oj)  
    - 4000-7000 words  
    - APC - None  
- emergent themes based on first 2 papers, which ***may*** include:   
    - technology for adaptive testing, automated item generation, large-scale assessments (NCLEX, PISA, FSA, etc)  
    - technology for surveillance or academic integrity (Turnitin, Proctorio, etc)  
    - technology to enable new forms of learning- and learner-centred assessments (portfolios, collaboration, version control, learner contributors)  
    - ethical applications of technology in assessment  

### Introduction  {-}

### Literature    {-}

### Theoretical / Conceptual Framework    {-}

### Research Method   {-}

### Analysis   {-}

### Findings and Limitations   {-}

### Discussion  {-}

### Impact on theory and/or practice   {-}

### Recommendations for future research   {-}

### Conclusion   {-}

### Data Availability   {-}

### References   {-}




## Proposed format(s) for completed dissertation:  {-}  
The following structure represents the minimal expectation for a 3-paper dissertation. Other chapters may become necessary, depending on the course of the studies and emergent themes.  

### Introduction (2000 words) {-}

### Paper 1 (4000-7000 words) {-}

### Paper 2 (4000-7000 words) {-}

### Paper 3 (4000-7000 words)  {-}

### Conclusions and Recommendations (2000-3000 words)  {-}

### References {-}

### Appendices {-}

## Oral Exam Format  {-}
- Covers all sections of the completed dissertation
- Responsible for all methods, findings, conclusions, and recommendations in all 3 papers

## Back-up Plan  {-} 
- should Paper 3 be abandoned (job opportunity emerges, etc.), then convert papers 1 and 2 into a monograph format. 

 

 
