# A Review of the Literature on Assessment in Technology-mediated Higher Education {-}


## Introduction {-}

Assessing learning is a critical component of the work of higher education instructors, yet not enough is known about how instructors plan for and make decisions about how they will assess their students' learning, particularly in the context of technology-mediated environments. In her important article, Shepard [-@shepardRoleAssessmentLearning2000] argued at the turn of the century that contemporary (at the time) assessment structures originated in past models of curriculum and instruction which were popular in the early 1900s. These curricular models emphasized the work of psychologists like Thorndike [@thorndikeElementsPsychology1905] and Skinner [@skinnerBehaviourOrganisms1938] who viewed the process of learning as being grounded in the mechanistic view of behaviourism where learning is the result of the precise and controlled input of 'knowledge' and reinforced with rewards for correct responses. As such, instructors (appropriately at the time) designed their assessments to align with the curricular goals of the time and assessed learning by determining whether or not a learner could provide the single correct response to a given question at a time removed from the instruction.  However, in the latter half of the 20th century, when western psychologists discovered the ideas of Lev Vygotsky [@vygotskyMindSociety1978], a contemporary of the previously mentioned psychologists, curricula began to take a more social-constructivist approach that emphasized higher-order thinking, problem-solving in social contexts, and metacognitive skills over rote memorization. Unfortunately, it seemed that the efficiencies of testing memory, recognition, and recall through selected-response tests were too deeply embedded in the practices of HE instructors who resisted changing their assessments to match the new curricular goals. Barnett [-@barnettWillLearnBeing2007] contends that these new goals lead to a state of *supercomplexity* with which both learners and instructors must grapple, and which Garrison et al. [-@garrisonThinkingCollaborativelyEducational2015] argue requires deep changes to how instructors approach teaching and how learners approach learning.

Shepard argues for the need to integrate assessment and instruction in such a way as to engage learners in authentic performance tasks more suited to modern understandings of cognition. It appears now that, in the twenty-two years since Shepard wrote her paper, the goals of early 21st century curricula have continued to diverge from those of the 20th century with the World Economic Forum identifying competencies in collaboration, analytical thinking, creative problem-solving, and continual learning as being priorities for 21st century employers [@worldeconomicforumFutureJobsReport2020].  Additionally, digital and networked technologies have become ubiquitous in society and higher education [@pellegrinoPerspectivesIntegrationTechnology2010; @webbAssessmentTwentyFirstCentury2018; @broadfootAssessmentTwentyFirstCenturyLearning2016] and the influence of digital technologies on instructors approaches to assessment remains under researched. Models of assessment which prioritize testing skills in a manner aligned with 20th century curricular models are no longer adequate because they no longer align with the priorities of modern higher education [@broadfootAssessmentTwentyFirstCenturyLearning2016; @crooksImpactClassroomEvaluation1988; @pellegrinoPerspectivesIntegrationTechnology2010; @timmisRethinkingAssessmentDigital2016].

Despite Shepard's exhortation to integrate modern curricular goals with aligned assessment practices, both local and systemic change in this area has been elusive [@broadfootAssessmentTwentyFirstCenturyLearning2016; @earlAssessmentLearningUsing2013]. This is in part because the approaches that individual instructors take to assessment are driven by complex factors at the individual level as well as local and systemic levels [@blackAssessmentClassroomLearning1998; @delucaDifferentialSituatedView2019; @willisConceptualisingTeachersAssessment2013]. The variety of factors, combined with the relative freedom instructors have to design their courses and assessments leads to approaches to assessment that are variable, idiosyncratic, and often influenced by individual instructors' past experiences rather than a deep understanding of assessment theory [@lipnevichWhatGradesMean2020; @masseyAssessmentLiteracyCollege2020].

<!--
[@wellerGoodOnlineLearning2022]
-->

{--Researchers are engaged in important work exploring how K12 teachers approach assessment in their classrooms, including DeLuca et al.'s [-@delucaApproachesClassroomAssessment2016] *Approaches to Classroom Assessment Inventory*, but there has been less work in relation to technology-mediated higher education. --}

Given the confluence of the preceding factors,  the purpose of this literature review will be to synthesize and analyze the literature related to approaches to assessment among higher education instructors. The review will begin with a survey of historical conceptions of assessment, followed by a deeper analysis of the literature since 2010 with a focus on assessment in technologically-mediated higher education.

This review is guided by four research questions:

1. What factors shape higher education instructors' approaches to assessment?
2. What are the major themes or patterns in the literature related to approaches to assessment in higher education?  
3. What are the major themes or patterns in the literature related to the impact of technology on assessment in higher education?  
4. What gaps exist in the literature related to approaches to assessment in technology-mediated higher education?

## A Brief History of Classroom Assessment Research {-}

There are deep and rich bodies of literature addressing educational assessment *writ large*, and it would not be possible in the scope of this article to adequately cover the full breadth and depth of the published research [@joughinAssessmentLearningJudgement2009a]. Consequently, while any starting point may seem somewhat arbitrary, the author chose to begin with the genesis of modern thinking of assessment being divided into "summative assessment" (for the purposes of providing a final judgement of learning) and "formative assessment" (for the purposes of providing feedback to learners and instructors to improve learning). This framing of assessment was popularized by Benjamin Bloom and remains prominent in the literature.

In exploring higher education instructors' approaches to assessment, it is helpful to look to research in the K12 sector as the idea of approaches to assessment originated in the context of K12 teaching. There have long been concerns that K12 teachers do not graduate with sufficient knowledge of assessment, even though they complete undergraduate degrees which have come to include specific courses in assessment [@stigginsAssessmentLiteracy1991]. Given this, in addition to the fact that higher education instructors generally do not encounter any specific pedagogical or assessment preparation in their graduate degrees, we can infer that the assessment capabilities of higher education instructors are not as advanced compared to those of K12 teachers. This is supported in research conducted by Massey et al. [-@masseyAssessmentLiteracyCollege2020] who investigated the impact of a semester-long instructional development course on the conceptions of assessment and assessment confidence of new faculty. Pre-course responses indicated a predominant view that assessment is primarily about summative testing to confirm that learners have retained information from didactic learning experiences. They found that the instructional development course encouraged faculty to deepen their understandings of assessment, and as they did so, their conceptions of assessment became more nuanced and complex. At the same time, following the increased depth in conceptions, researchers noted that participants' confidence in assessment also increased.

Among the more influential publications related to modern views of assessment (then usually called "evaluation") was Scriven's [-@scrivenMethodologyEvaluation1967] article in which he drew distinctions between "formative" and "summative" evaluation. Formative evaluation was described as evaluation for the purposes of improvement, and summative evaluation was seen as a validation of the quality of work at the end of a process. This distinction was quickly incorporated into Bloom's [-@bloomLearningMasteryInstruction1968] ideas related to mastery learning and began to be promoted as a model for educational reform. However, by the late 1990s, when Black and Wiliam [-@blackAssessmentClassroomLearning1998] published their landmark review of the literature on assessment, the idea of formative assessment was still not well-defined or implemented. Black and Wiliam framed formative assessment as "encompassing all those activities undertaken by teachers, and/or by their students, which provide information to be used as feedback to modify the teaching and learning activities in which they are engaged" [-@blackAssessmentClassroomLearning1998, p. 7-8]. Although Black and Wiliam came to very strongly-stated conclusions about the value of formative assessments (e.g. "The research reported here shows conclusively that formative assessment does improve learning. The gains in achievement appear to be quite considerable, and as noted earlier, amongst the largest ever reported for educational interventions." [-@blackAssessmentClassroomLearning1998, p. 61]), reliance on summative assessments in HE remained high [@harlenSystematicReviewImpact2002; @lipnevichWhatGradesMean2020; @hebertOnlineRemoteProctoring2021].

Also towards the end of the 20th century, the idea of *assessment literacy* was introduced by Richard Stiggins[-@stigginsAssessmentLiteracy1991]. Stiggins argued that, in K12 educational contexts, society had come to expect high educational attainment, but teacher education programs did little or nothing to prepare graduates to be able to certify that their learners were actually meeting targets. Stiggins blamed this in part on the fact that in the United States, there was no specific requirement for teachers to be trained in assessment, and consequently, teachers, administrators, and those who train them were essentially assessment illiterate. Stiggins described assessment literate educators as those who "have a basic understanding of the meaning of high- and low quality assessment and are able to apply that knowledge to various measures of student achievement" (p. 535).

An intuitive reading of this history suggests that the decade of the 1990s and into the early 2000s may have been pivotal in determining the direction of the discourse in assessment for the following 10-15 years. The 1990s were bookended by Stiggins' article in 1991 and Black and Wiliam's review in 1998. The emphasis on professional standards and skill-based assessment literacy, in alignment with Stiggins' article, dominated teacher education programs in the 1990s and for the 20 years following. However, Black and Wiliams' 1998 review of the literature and recommendations promoted a significantly greater emphasis on formative assessment [-@brookhartEducationalAssessmentKnowledge2011]. The following sections trace the development of assessment literacy and then the published literature on formative assessment. 

### Professional Standards / Assessment Literacy {-}

The recognition of assessment literacy as a critical competency for educators was influenced by the growing demands for teacher and school accountability in the post-WWII era in the USA and Canada, particularly the *Elementary and Secondary Education Act* (ESEA), passed in 1965, and the *No Child Left Behind* (NCLB) act, passed in 2002 [see @delucaPreparingTeachersAge2012 for a detailed discussion]. As such, conceptualizations of assessment literacy tended to be based on sets of standards to which K-12 teachers were obligated. Table 1 provides a brief overview of each of the sets of standards published between 1990 and 2015, including Brookhart's [-@brookhartEducationalAssessmentKnowledge2011] critique of the 1990 *Standards* as being too focused on 20<sup>th</sup> century skills, rather than formative assessment practices and 21<sup>st</sup> century pedagogies. See Appendix A for a full listing of each of the standards and their constituent skills or characteristics.

**Table 1**

*Assessment Standards Compared*

| Title/Article  Citation | Description |
|------|------|
| Standards for Teacher Competence in Educational Assessment of Students  [@aftStandardsTeacherCompetence1990] | The initial set of standards, published by a committee of representatives from the American Federation of Teachers, the National Council on Measurement in Education, and the National Education Association. The *Standards* are a list of seven skills expected of teachers.  |
| Principles for Fair Student Assessment Practices for Education in Canada [@jointadvisorycommitteePrinciplesFairStudent1993] | A group of Canadian educators published the *Principles for Fair Student Assessment Practices for Education in Canada*, Part A of which was a list of 37 guidelines related to five principles of fair student classroom assessment and was based on the 1990 *Standards* (see Appendix A). Part B was focused on externally-developed standardized tests. |
| Assessment Literacy For the 21st Century  [@stigginsAssessmentLiteracy21st1995] |  Stiggins outlined five characteristics of sound assessments.|
| Educational Assessment Knowledge and Skills for Teachers  [@brookhartEducationalAssessmentKnowledge2011] | Twenty years following the publication of the *Standards*, Brookhart [-@brookhartEducationalAssessmentKnowledge2011] argued that the 1990 *Standards* had become outdated because they did not address either the growing practices and ideas of formative assessment (assessment *for* and *as* learning) or standards-based assessment and that they needed to be revised. Brookhart suggested a list of 11 skills (see Appendix A) to adjust the focus of the 1990 *Standards* to be in greater alignment with more modern conceptions of assessment. | 
| Classroom Assessment Standards for PreK-12 Teachers  [@klingerClassroomAssessmentStandards2015] | Finally, in 2015, the Joint Committee on Standards for Educational Evaluation (JCSEE), with key representatives from both Canada and the USA, published the most recent set of standards, called the *Classroom Assessment Standards for PreK-12 Teachers* (see Appendix A). The JCSEE standards are grouped into three broad domains (foundations, use, and quality), each with five or six related standards. |

The policy environment in the United States combined with assessment research and the publication of various sets of standards as highlighted above served to promote an emphasis on measuring outcomes using standardized tests and using the results from those tests as data points for evaluating teacher and administrator competence [@brookhartEducationalAssessmentKnowledge2011].  

### Formative Assessment {-}

Following Black and Wiliam's [-@blackAssessmentClassroomLearning1998] review, the National Research Council's (NRC) 2001 foundational report *Knowing What Students Know: The Science and Design of Educational Assessment*, (hereafter, the *NRC report*) advanced understanding of assessment with their definition of assessment as "reasoning from evidence" [-@pellegrinoKnowingWhatStudents2001, p. 43], or, more specifically "a process of drawing reasonable inferences about what students know on the basis of evidence derived from observations of what they say, do, or make in selected situations" [@pellegrinoKnowingWhatStudents2001, p. 112], based on Mislevy's [-@mislevyTestTheoryReconcieved1994, p. 4] assertion that "test theory is machinery for reasoning from students' behavior to conjectures about their competence, as framed in a particular conception of competence." Such a parsimonious description, however, may hide some of the complexities of fairly and equitably coming to know what learners know and can do in relation to particular outcomes. Since knowledge of a particular domain cannot be directly observed in a learner, and therefore cannot be quantified, instructors must rely on data gathered during the teaching process to support a particular inference about what a learner *probably* knows. The data gathered from performance tasks such as exams, essays, portfolios, labs, etc, become *evidence* when they support an inference about what a learner knows and can do [@blackClassroomAssessmentPedagogy2018]. 

The *NRC* report, which Black played a role in creating, used Black and Wiliam's review quite prominently throughout in building the argument for formative assessment as opposed to a primary reliance on summative testing (see pp. 31, 38, 41, 226, 235, and 236). Pellegrino et al. [-@pellegrinoKnowingWhatStudents2001] highlight that there are multiple purposes for assessment, assessment to assist learning, assessment of individual acheivement, and assessment to evaluate programs. They argue that it is important to recognize that not all assessments fit with all purposes of assessment, and that the more purposes an assessment is intended to serve, the less likely it is to serve all purposes well. Black and Wiliam note that these multiple purposes create tension for teachers who must navigate and align diverse purposes. However, as some jurisdictions have prioritized summative assessment structures to fulfil the purposes of assessing individual achievement and evaluating programs, it is often the case that the purpose of serving the learning needs of learners is sacrificed.

In the first decade of the 21<sup>st</sup>, researchers increasingly recognized the complexity of assessment practices and the factors which drive them. Brown [-@brownTeachersConceptionsAssessment2004] showed in a study of K12 teachers in New Zealand that teachers' "conceptions of assessment" (p. 302), or the organizing frameworks teachers use to understand the phenomenon of assessment, are not simple constructs, but are complex and interconnected. Brown's model showed four common conceptions of assessment among K12 teachers:

- improvement of teaching and learning,  
- school accountability,  
- student accountability, or  
- treating assessment as irrelevant.

While Brown's model nods at formative assessment in mentioning improvement in teaching and learning, there remained a strong emphasis on accountability for learners, teachers, and schools. However, as thinking progressed, James [-@jamesAssessmentLearning2008] highlighted important connections between assessment practices and learning theory, noting that both behaviourism and cognitivism emphasize the acquisition of knowledge as a sort of commodity and thus both lead to assessment strategies that emphasize the individual reproduction of knowlege that has either been taught, or has been constructed in meaning-making exercises. Contrary to these approaches, socio-cultural learning theory emphasizes the communal production of meaning through social tools and social interactions between peers and more capable 'others' [@vygotskyMindSociety1978]. Thus, assessment in socio-cultural contexts, which James argues is under-theorized, ought to be holistic and situated within the communal learning process, rather than an event that happens sometime after the learning has happened. Similarly, Fletcher et al. [-@fletcherFacultyStudentsConceptions2012] note that teachers who view teaching as the transmission of knowledge tend to rely more heavily on assessment tasks which require learners to reproduce what they have been taught. On the other hand, teachers who take a more socio-constructivist view that knowledge is built over time tend to conceive of assessment as being an integral part of the teaching and learning process as opposed to a culminating activity.

The second decade of the 21<sup>st</sup> century marked a further turn towards more complex theories of assessment and an emphasis on formative assessment. Brookhart [-@brookhartEducationalAssessmentKnowledge2011] published her influential article criticizing the overemphasis on dated forms of assessment and proposed an updated set of eleven standards which included much greater emphasis on formative assessment skills. Earl [-@earlAssessmentLearningUsing2013] commented that the various purposes of assessment might sometimes conflict with each other, such as when assessment might be used for both formative feedback and also as evidence supporting a summative grade. Earl contends that the purposes of assessment can be categorized as assessment *of* learning (summative judgements of learner knowledge), assessment *for* learning (formative feedback loops guiding and directing future learning), and assessment *as* learning (learners using metacognitive skills to self-regulate in learning contexts). While Earl's taxonomy is primarily focused on how instructors and learners use assessment data, others note that conceptions of assessment extend well beyond this. DeLuca et al.[-@delucaEstablishingFoundationValid2013], for example, proposed that there are four predominant conceptions of assessment among teachers, namely, "(a) assessment as testing, (b) assessment as format, (c) assessment as purpose and (d) assessment as process" (p. 110). They argue that their taxonomy represents an ordered progression of complexity beginning with a primary focus on summative testing and progressing through to a conception of assessment that recognizes the complexity of integrated teaching and learning processes. 

The most recent set of standards, published by the Joint Committee on Standards for Educational Evaluation [@klingerClassroomAssessmentStandards2015] represents a further break from the former mindset of assessment as measurement and focused on three areas. First is the foundational knowledge needed to understand the purposes of assessment and how to design assessments that allow learners to demonstrate their ability and to communicate results with stakeholders. The second area of required competence is in the use of assessment data to analyze learner performance and provide formative feedback to improve future performance. The third area has to to with the quality of assessments such that they are culturally and linguistically appropriate, account for the differential needs of all learners, that they are unbiased, reliable, and support valid interpretations of assessment data and finally that they are continually revised and updated to improve overall quality.

This brief overview of various sets of standards, while incomplete, provides a picture of how researchers studying assessment have come to view assessment as a much more holistic and whole-person endeavour for both teachers and learners compared to early views emphasizing measurement grounded in behaviourist pedagogies.







### Approaches to Assessment {-}

In the context of this progression towards more formative assessment practices, other researchers began exploring the complexities of assessment by considering the many factors that comprise individual teachers' approaches to assessment. DeLuca et al. [-@delucaTeachersApproachesClassroom2016] used their earlier framework of conceptions of assessment [-@delucaEstablishingFoundationValid2013] and proposed the idea of *approaches to assessment*. DeLuca et al. [-@delucaTeachersApproachesClassroom2016], citing [@newtonClarifyingPurposesEducational2007] argue that the varying conceptions of assessment as well as the large number of factors that shape teachers' approaches to assessment, all of which can be contradictory, created confusion and possibly hindered the progressive development of teachers' competency in assessment. The idea of *approaches to assessment* is grounded in the complexity of assessment as well as researchers' recognition that skill-based sets of standards fail to account for all of the factors shaping assessment practice in modern schools. 

The *Approaches to Classroom Assessment* model is based on the JCSEE standards [@klingerClassroomAssessmentStandards2015] and describes four themes of AL, each with three dimensions. The model represents somewhat of a break from previous models in that it references *approaches to assessment* rather than *assessment literacies*. This is a reflection of the authors' view that language around *literacies* and *competencies* may indicate a reliance on "correct" views or methods rather than the complex array of influences that lead to multiple legitimate approaches as identified in the literature [@delucaDifferentialSituatedView2019; @willisConceptualisingTeachersAssessment2013].

The themes DeLuca et al. [-@delucaExploringAssessmentCultures2021, p. 10] describe along with their associated dimensions are listed below and illustrated in figure 2:

1. Assessment purposes.  
     - Assessment *of* learning  
       - Teachers' use of evidence to summate student learning and assign a grade in relation to students' achievement of learning objectives  
     - Assessment *for* learning  
       - Teachers' and students' use of evidence to provide feedback on progress towards learning objectives (i.e., inform next steps for learning and instructions).  
       - Involves both teacher-directed and student-centred approaches to formative assessment.  
     - Assessment *as* learning  
       - Focuses on how the student is learning by providing feedback or experiences that foster students' metacognitive abilities and learning skills (e.g., self-assessment, goal-setting, learning plans).  
       - Involves teachers but is primarily student-centred.  
2. Assessment process  
     - Design  
       - Focuses on the development of reliable assessments and items that measure student learning in relation to learning objectives.  
     - Use/scoring  
       - Focuses of the adjustment and use of scoring protocols and grading schemes to respond to assessment scenarios.  
     - Communication  
       - focuses on the interpretation of assessment results and feedback through communication to students and parents.  
3. Assessment fairness  
     - Standard  
       - Maintains the equal assessment protocols for all students.  
     - Equitable  
       - Differentiates assessment protocols for formally identified students (i.e., special education or English language learners)  
     - Differentiated  
       - Individualizes learning opportunities and assessments that address each student's unique learning needs and goals.  
4. Assessment theory  
     - Consistent  
       - Works to ensure consistency in results within assessments, across time periods, and between teachers.  
     - Contextual  
       - Works to ensure assessment or evaluation measures what it claims to measure (i.e., learning objectives) and promote valid interpretations of results.  
     - Balanced  
       - Works to ensure consistency in measuring what an assessment or evaluation intends to measure, and degree to which an assessment or evaluation measures what it claims to measure.  

![Figure 1. Approaches to Assessment [@delucaExploringAssessmentCultures2021]](images/approaches-2-assessment.png)

DeLuca et al. [-@delucaApproachesClassroomAssessment2016, p 252] initially proposed three general approaches to classroom assessment aligning with the four themes listed above.

Table 2. Assessment Literacy Themes with Associated Approaches to Assessment

|   | Approaches to Assessment|   |   |
|---|---|---|---|
|Assessement Literacy Theme | Approach A | Approach B | Approach C |
| Assessment Purposes | Assessment of Learning | Assessment for Learning | Assessment as Learning|
| Assessment Processes | Design | Use/Scoring | Communication |
| Assessment Fairness | Standard treatment | Equitable treatment | Differentiated approach|
| Measurement Theory | Reliability  | Validity | Reliability/Validity |

To this point in the present review, much of the emphasis has covered assessment research in K12 contexts, as DeLuca et al.'s [-@delucaTeachersApproachesClassroom2016] model was developed in the context of assessment in K12 schools and teachers. As it is a new model, and not developed with teaching in higher education as a primary focus, it has not been scrutinised to the same degree in higher education. That said, there is overlap between assessment research in higher education and K12 as many ideas that originate in the K12 literature end up influencing researchers in higher education. Presumably this is an outcome of a greater degree of professionalisation and regulation of teaching at the K12 level compared to higher education.

<!--
DeLuca et al.'s model [-@delucaApproachesClassroomAssessment2016], *approaches to classroom assessment* could be seen to align with the *assessment* component of Biggs' 3P model of teaching and learning [-@biggsWhatStudentDoes1999; -@biggsTheoryPracticeCognitive1993] and so aligns well with a concise model of teaching and learning in higher education.
-->

## Factors Affecting Higher Education Instructors Approaches to Assessment {-}



Popham [-@pophamAssessmentLiteracyTeachers2009] describes two often competing types of assessments, *classroom* assessments and *accountability* assessments. Classroom assessments are typically teacher-created, although some teachers use publisher-created materials such as test banks, and are used to assign grades to learners or to inform future instruction. Accountability assessments are those which are usually government-imposed, standardized tests, most often deployed in K12 settings, although there are notable higher education contexts where such accountability tests are prominent, namely programs which prepare learners for external regulatory exams (e.g. nursing, accounting). Popham argues that the relative emphasis on either of these types of assessment will impact the decisions teachers make in their instructional and assessment approaches. 

Offerdahl and Tomanek [-@offerdahlChangesInstructorsAssessment2011] investigated instructors' assessment thinking in relation to being presented with new assessment strategies. They found that changes in assessment *practice* didn't necessarily follow from changes in assessment *thinking* and that there are many factors which influence both assessment thinking and practice.

Willis et al. [-@willisConceptualisingTeachersAssessment2013] highlight the importance of understanding assessment literacies (plural) as being understood in relation to learning theory and that assessment is an "ethical practice that is social, dynamic, and layered" (p. 242). They situate their discussion in the idea of "horizontal" and "vertical" discourses as articulated by Bernstein [-@bernsteinVerticalHorizontalDiscourse1999]. A horizontal discourse is characterized as being common sense knowledge that is presumed to be known by local communities. It is context dependent and can be contradictory across communities while remaining internally coherent within communities. Bernstein contrasts this with the idea of vertical discourses, which are characteristically organized in a hierarchy with explicit principles which are systematically enacted (such as in the sciences) or rely on "a series of specialised languages with specialised modes of interrogation and specialised criteria for the production and circulation of texts" [@bernsteinVerticalHorizontalDiscourse1999, p. 159], as in the social sciences. As vertical discourses rely on specialized language and expertise, they must be "decoded or translated (pedagogised)" [@singhPedagogisingKnowledgeBernstein2002, p. 4] in order for those outside the domain to access that particular knowledge. Willis et al. [-@willisConceptualisingTeachersAssessment2013] argue that, since teachers are influenced by both horizontal and vertical discourses, they must constantly work to balance vertical and horizontal discourses. They use the example of the vertical discourse reflected in the "measurement conception of assessment" [-@willisConceptualisingTeachersAssessment2013 p. 244] in which assessment is viewed in light of positivist scientific paradigms, behaviourist learning theory, and an emphasis on testing learning at a time removed from instruction. This discourse is seen prominently in Confucian traditions [@carlessTestingProductiveStudent2011], as well as cultures that use high-stakes testing for learner advancement and teacher accountability, such as the USA [@pophamAssessmentLiteracyTeachers2009]. Contrary to this prominent vertical discourse is the horizontal discourse grounded in socio-cultural perspectives exemplified in local cultures which downplay the role of high-stakes testing and instead focus on assessment as an integral component of learning [@delucaAssessmentLiteracyDevelopment2010].

Looney et al. [-@looneyReconceptualisingRoleTeachers2017] argue that teacher assessment literacy is too instrumental a focus and that *conceptions of assessment* tend to neglect affective feelings related to teacher self-efficacy. They argue that teacher assessment identity encompasses these factors and that there are significant ontological dimensions to assessment. Teachers assess the way they do because of *who* they are in addition to what they know and are able to do.

[@delucaPoliciesProgramsPractices2019]


### Assessment Cultures {-}

[@masseyAssessmentLiteracyCollege2020] 

[@birenbaumConceptualizingAssessmentCulture2014] - assessment for learning cycle corresponds to inquiry sycle

[@delucaExploringAssessmentCultures2021]
[@birenbaumAssessmentCultureTesting2016]

[delucaCrossculturalComparisonGerman2020]
[willisConceptualisingTeachersAssessment2013]
[@hebertOnlineRemoteProctoring2021]


### Impact Of Technology On Approaches To Assessment In Higher Education  {-}

While digital technologies have become ubiquitous in higher education [@broadfootAssessmentTwentyFirstCenturyLearning2016], research suggests that the impact of technology on pedagogy, including assessment practices, in higher education has not kept up with the potential. Garrison et al. [-@garrisonThinkingCollaborativelyEducational2015] introduce the idea of *shared metacognition* as being a necessary competency for learners in 21st century higher education. They build a case that modern learners must contend with *supercomplexity* [@barnettWillLearnBeing2007], which refers to the open-endedness and ambiguity characteristic of modern society and culture. Supercomplexity is both compounded and mitigated through the integration of digital technologies in higher education. While there is additional cognitive load associated with learning to learn through technology, it is also true that technology can help learners organize information through *cognitive offloading* [@riskoCognitiveOffloading2016]. Supercomplexity requires learners to engage in both cognitive offloading and shared metacognition in order to be successful, especially in light of the goals of modern universities.

Garrison et al. employ the same argument as Shepard [-@shepardRoleAssessmentLearning2000] when they assert that modern technology-mediated learning environments tend to be grounded in out-dated approaches.


Some researchers use terms, such as "technology-*enhanced*", "technology-*enabled*, or "technology-*rich*" [@eyalDigitalAssessmentLiteracy2012, p. 37] assessment, which show a positivity bias towards the use of technology in higher education. Although this terminology will be a component of the search process, this review will use the more neutral term "technology-mediated assessment" whenever possible in light of the fact that assessment is not always "enhanced", "enabled", or "enriched" with the use of technology.

Modern universities are under pressure from public and private funding agencies [@hebertOnlineRemoteProctoring2021] and employers to demonstrate that graduates are equipped for the demands of citizenship in the 21st century [@pellegrinoPerspectivesIntegrationTechnology2010]. Technological changes in society have impacted how people live, work, play, and learn in many ways leading to additional pressures on universities to respond to new realities [@worldeconomicforumFutureJobsReport2020]. As a result, universities have incorporated many technologies into how they operate, including student information systems, faculty career tracking systems, and learning management systems, to name a few. Technologies have also impacted how instructors teach, with many instructors incorporating digital tools such as the aforementioned learning management systems, but also in-class slide-decks to accompany lectures (often replacing older technologies, such as overhead projectors and chalk boards), digital response systems, digital distribution and gathering of documents, digital feedback, networked learning environments (i.e., blogs, git-based repositories, wikis, and other collaborative digital learning environments), and, more recently, artificially intelligent agents and algorithms used to interact with learners and even evaluate learner artifacts. Many of these technologies have allowed both universities and instructors to automate, and therefore scale up, processes and procedures that formerly consumed significant time and labour, however, in most cases, they have not fundamentally changed the kind of work that is being done [@broadfootAssessmentTwentyFirstCenturyLearning2016]. For example, automated grading of selected-response tests using a learning management system or a bubble sheet has greatly reduced the amount of time it takes to score selected-response tests, saving instructors significant time. However, this technology has not fundamentally changed the selected-response test itself. Similarly, collecting digital artifacts, like essays, has improved tracking and likely reduced the number of lost essays, but it has not fundamentally changed the nature of the assessment task. Despite the widespread adoption of technologies for many tasks in higher education, it would seem that technology has not yet significantly transformed how instructors encourage or assess learning in their classes [@garrisonThinkingCollaborativelyEducational2015].
