# Appendix A {-}

Select Standards for Educational Assessment

## Standards for Teacher Competence in Educational Assessment of Students

1. Teachers should be skilled in *choosing* assessment methods appropriate for instructional decisions.
2. Teachers should be skilled in *developing* assessment methods appropriate for instructional decisions.
3. The teacher should be skilled in administering, scoring, and interpreting the results of both externally-produced and teacher-produced assessment methods.
4. Teachers should be skilled in using assessment results when making decisions about individual students, planning teaching, developing curriculum, and school improvement.
5. Teachers should be skilled in developing valid pupil grading procedures which use pupil assessments.
6. Teachers should be skilled in communicating assessment results to students, parents, other lay audiences, and other educators.
7. Teachers should be skilled in recognizing unethical, illegal, and otherwise inappropriate assessment methods and uses of assessment information.

National Council on Measurement in Education, American Federation of Teachers, & National Education Association. (1990). Standards for Teacher Competence in Educational Assessment of Students. https://eric.ed.gov/?id=ED323186

---

## Principles for Fair Student Assessment Practices for Education in Canada


### Developing and Choosing Methods for Assessment
1. Assessment methods should be developed or chosen so that inferences drawn about the knowledge, skills, attitudes, and behaviors possessed by each student are valid and not open to misinterpretation.
2. Assessment methods should be clearly related to the goals and objectives of instruction, and be compatible with the instructional approaches used.
3. When developing or choosing assessment methods, consideration should be given to the consequences of the decisions to be made in light of the obtained information.
4. More than one assessment method should be used to ensure comprehensive and consistent indications of student performance.
5. Content and language that would generally be viewed as sensitive, sexist, or offensive should be avoided.
6. Assessment instruments translated into a second language or transferred from another context or location should be accompanied by evidence that inferences based on these instruments are valid for the intended purpose.

### Collecting Assessment Information
1. Students should be told why assessment information is being collected and how this information will be used.
2. An assessment procedure should be used under conditions suitable to its purpose and form.
3. In assessments involving observations, checklists, or rating scales, the number of characteristics to be assessed at one time should be small enough and concretely described so that the observations can be made accurately.
4. The directions provided to students should be clear, complete, and appropriate for the ability, age, and grade level of the students.
5. In assessment involving selection items (e.g., true-false, multiple-choice), the directions should encourage students to answer all items without threat of penalty.
6. When collecting assessment information, interactions with students should be appropriate and consistent.
7. Unanticipated circumstances that interfere with the collection of assessment information should be noted and recorded.
8. A written policy should guide decisions about the use of alternate procedures for collecting assessment information from students with special needs and students whose proficiency in the language of instruction is inadequate for them to respond in the anticipated manner.

### Judging and Scoring Student Performance
1. Before an assessment method is used, a procedure for scoring should be prepared to guide the process of judging the quality of a performance or product, the appropriateness of an attitude or behavior, or the correctness of an answer.
2. Before an assessment method is used, students should be told how their responses or the information they provide will be judged or scored.
3. Care should be taken to ensure that results are not influenced by factors that are not relevant to the purpose of the assessment.
4. Comments formed as part of scoring should be based on the responses made by the students and presented in a way that students can understand and use them.
5. Any changes made during scoring should be based upon a demonstrated problem with the initial scoring procedure. The modified procedure should then be used to rescore all previously scored responses.
6. An appeal process should be described to students at the beginning of each school year or course of instruction that they may use to appeal a result.

### Summarizing and Interpreting Results
1. Procedures for summarizing and interpreting results for a reporting period should be guided by a written policy.
2. The way in which summary comments and grades are formulated and interpreted should be explained to students and their parents/guardians.
3. The individual results used and the process followed in deriving summary comments and grades should be described in sufficient detail so that the meaning of a summary comment or grade is clear.
4. Combining disparate kinds of results into a single summary should be done cautiously. To the extent possible, achievement, effort, participation, and other behaviors should be graded separately.
5. Summary comments and grades should be based on more than one assessment result so as to ensure adequate sampling of broadly defined learning outcomes.
6. The results used to produce summary comments and grades should be combined in a way that ensures that each result receives its intended emphasis or weight.
7. The basis for interpretation should be carefully described and justified.
8. Interpretations of assessment results should take account of the backgrounds and learning experiences of the students.
9. Interpretations of assessment results should take account of the backgrounds and learning experiences of the students.
10. Interpretations of assessment results should be made with due regard for limitations in the assessment methods used, problems encountered in collecting the information and judging or scoring it, and limitations in the basis used for interpretation.

### Reporting Assessment Findings
1. The reporting system for a school or jurisdiction should be guided by a written policy. Elements to consider include such aspects as audiences, medium, format, content, level of detail, frequency, timing, and confidentiality.
2. Written and oral reports should contain a description of the goals and objectives of instruction to which the assessments are referenced.
3. Reports should be complete in their descriptions of strengths and weaknesses of students, so that strengths can be build upon and problem areas addressed.
4. The reporting system should provide for conferences between teachers and parents/guardians. Whenever it is appropriate, students should participate in these conferences.
5. An appeal process should be described to students and their parents/guardians at the beginning of each school year or course of instruction that they may use to appeal a report.
6. Access to assessment information should be governed by a written policy that is consistent with applicable laws and with basic principles of fairness and human rights.
7. Transfer of assessment information from one school to another should be guided by a written policy with stringent provisions to ensure the maintenance of confidentiality.

Source: Joint Advisory Committee. (1993). Principles for Fair Student Assessment Practices for Education in Canada. University Of Alberta. https://www.wcdsb.ca/wp-content/uploads/sites/36/2017/03/fairstudent.pdf

---

## Characteristics of sound assessments

Sound assessments
1. arise from and serve clear purposes;
2. arise from and reflect clear and appropriate achievement targets;
3. rely on a proper assessment method, given the purpose and the target;
4. sample student achievement appropriately; and
5. control for all relevant sources of bias and distortion. 

Source: Stiggins, R. J. (1995). Assessment Literacy for the 21st Century. *The Phi Delta Kappan, 77*(3), 238–245. JSTOR.

---


## Educational assessment knowledge and skills for teachers



1. Teachers should understand learning in the content area they teach.
2. Teachers should be able to articulate clear learning intentions that are congruent with
both the content and depth of thinking implied by standards and curriculum goals, in such a way that they are attainable and assessable.
3. Teachers should have a repertoire of strategies for communicating to students what
achievement of a learning intention looks like.
4. Teachers should understand the purposes and uses of the range of available assessment
options and be skilled in using them.
5. Teachers should have the skills to analyze classroom questions, test items and
performance assessment tasks to ascertain the specific knowledge and thinking skills
required for students to do them.
6. Teachers should have the skills to provide effective, useful feedback on student work.
7. Teachers should be able to construct scoring schemes that quantify student performance on classroom assessments into useful information for decisions about students, classrooms, schools, and districts. These decisions should lead to improved student learning, growth, or development.
8. Teachers should be able to administer external assessments and interpret their results for
decisions about students, classrooms, schools, and districts.
9. Teachers should be able to articulate their interpretations of assessment results and their
reasoning about the educational decisions based on assessment results to the educational populations they serve (student and his/her family, class, school, community).
10. Teachers should be able to help students use assessment information to make sound
educational decisions.
11. Teachers should understand and carry out their legal and ethical responsibilities in assessment as they conduct their work.

Source: Brookhart, S. M. (2011). Educational assessment knowledge and skills for teachers. Educational Measurement: Issues and Practice, 30, 3–12. https://doi.org/10/cwcqj4

---

## Classroom Assessment Standards for PreK-12 Teachers

### Foundation

1. Assessment Purpose: Classroom assessment practices should have a clear purpose that supports teaching and learning.
2. Learning Expectations: Learning expectations should form the foundation for aligning classroom assessment practices with appropriate instruction and learning opportunities for each student.
3. Assessment Design: The types and methods of classroom assessment used should clearly allow students to demonstrate their learning.
4. Student Engagement in Assessment: Students should be meaningfully engaged in the assessment process and use of the assessment evidence to enhance their learning.
5. assessment Preparation: Adequate teacher and student preparation in terms of resources, time, and learning opportunities should be a part of classroom assessment practices,
6. Informed Students and Parents/Guardians: The purposes and uses of classroom assessment should be communicated to students and, when appropriate, parents/guardians.

### Use

1. Analysis of Student Performance: The methods for analyzing evidence of student learning should be appropriate for the assessment purpose and practice.
2. Effective Feedback: Classroom assessment practices should provide timely and useful feedback to improve student learning.
3. Instructional Follow-up: Analysis of student performance should inform instructional planning and next steps to support ongoing student learning.
4. Grades and Summary Comments: Summative grades and comments should reflect student achievement of the learning expectations.
5. Reporting: Assessment reports should be based on a sufficient body of evidence and provide a summary of a student's learning in a clear, timely, accurate, and useful manner.  

### Quality

1. Cultural and linguistic diversity: Classroom assessment practices should be responsive to and respectful of the cultural and linguistic diversity of students and their communities.
2. Exceptionality and special education: Classroom assessment practices should be appropriately differentiated to meet the specific educational needs of all students.
3. Unbiased and fair assessment: Classroom assessment practices and subsequent decisions should be free from all factors unrelated to the intended purposes of the assessment.
4. Reliability and validity: Classroom assessment practices should provide consistent, dependable, and appropriate information that supports sound interpretations and decisions about each student's knowledge and skills,
5. Reflection: Classroom assessment practices should be monitored and revised to improve their overall quality.

Klinger, D., McDivitt, P., Howard, B., Rogers, T., Munoz, M., & Wylie, C. (2015). Classroom Assessment Standards for PreK-12 Teachers. Joint Committee on Standards for Educational Evaluation. https://www.amazon.ca/Classroom-Assessment-Standards-PreK-12-Teachers-ebook/dp/B00V6C9RVO?asin=B00V6C9RVO&revisionId=d45424dd&format=1&depth=1
