# A Review of the Literature on Assessment in Technology-mediated Higher Education {-}

<!--
- [A Review of the Literature on Assessment in Technology-mediated Higher Education {-}](#a-review-of-the-literature-on-assessment-in-technology-mediated-higher-education--)
  - [Topic {-}](#topic--)
  - [Problem {-}](#problem--)
  - [Purpose {-}](#purpose--)
  - [Questions {-}](#questions--)
  - [Defining Assessment {-}](#defining-assessment--)
    - [Historical Definitions {-}](#historical-definitions--)
      - [Section Abstract{-}](#section-abstract-)
    - [Modern Conceptions of Assessment {-}](#modern-conceptions-of-assessment--)
      - [Section Abstract{-}](#section-abstract--1)
  - [Assessment Literacy {-}](#assessment-literacy--)
      - [Section Abstract{-}](#section-abstract--2)
  - [Approaches to Assessment {-}](#approaches-to-assessment--)
      - [Section Abstract{-}](#section-abstract--3)
  - [Assessment and Measurement  {-}](#assessment-and-measurement---)
      - [Section Abstract {-}](#section-abstract--)
    - [Validity {-}](#validity--)
    - [Reliability  {-}](#reliability---)
    - [Fairness {-}](#fairness--)
  - [Assessment in Higher Education  {-}](#assessment-in-higher-education---)
      - [Section Abstract {-}](#section-abstract---1)
  - [Impact of Technology on Assessment in Higher Education  {-}](#impact-of-technology-on-assessment-in-higher-education---)
-->

## Topic {-}

- Approaches to assessment in technology-mediated higher education  

## Problem {-}

- We don't know how higher education instructors approach classroom assessment in technologically-mediated environments.

<!--
- We don't know how the increased use of technology in higher education has impacted higher education instructors' approaches to assessment.  
-->

## Purpose {-}

- the purpose of this literature review will be to analyze, synthesize and critique the literature since 2010 related to how instructors in higher education approach classroom assessment in increasingly technology-mediated environments.  

## Questions {-}

1. What are the major themes or patterns in the literature related to approaches to assessment in higher education?  
2. What are the major themes or patterns in the literature related to the impact of technology on assessment in higher education?  
3. What gaps exist in the literature related to approaches to assessment in technology-mediated higher education?  

## Defining Assessment {-}

### Historical Definitions {-}

#### Section Abstract{-}

> The literature on assessment has evolved significantly since the mid 20th-century, from being primarily focused on quantifying and measuring learning, to more complex models of assessment incorporating both formative and summative purposes of assessment, setting the stage for modern views of assessment.

- Among the more influential publications related to modern views of assessment (then usually called "evaluation") was Scriven's [-@scrivenMethodologyEvaluation1967] article in which he drew distinctions between "formative" and "summative" evaluation.  
- This distinction was quickly incorporated into Bloom's [-@bloomLearningMasteryInstruction1968] ideas related to mastery learning and began to be promoted as a model for educational reform.  
- However, by the late 1990s, when Black and Wiliam [-@blackAssessmentClassroomLearning1998] published their thorough review of the literature, the idea of formative assessment was still not well-defined or implemented. Black and Wiliam framed formative assessment as "encompassing all those activities undertaken by teachers, and/or by their students, which provide information to be used as feedback to modify the teaching and learning activities in which they are engaged" [-@blackAssessmentClassroomLearning1998, p. 7-8].  
- The National Research Council's (NRC) 2001 report *Knowing what students know*, advanced understanding of assessment with their definition of assessment as "a process of drawing reasonable inferences about what students know on the basis of evidence derived from observations of what they say, do, or make in selected situations" [@pellegrinoKnowingWhatStudents2001, p. 112] or, more simply, "reasoning from evidence" [@pellegrinoKnowingWhatStudents2001, p. 43], based on Mislevy's assertion that "test theory is machinery for reasoning from students' behavior to conjectures about their competence, as framed in a particular conception of competence." [-@mislevyTestTheoryReconcieved1994 p. 4].  
- The NRC [@pellegrinoKnowingWhatStudents2001] models assessment as a triangle composed of three interdependent components of any assessment (Figure 1):  *cognition*, or a model of the domain to be learned; *observation*, or the performance task learners will complete to demonstrate their competence; and an *inference* or *interpretation* of the data produced by the observation. The interdependent nature of the three components requires that both the observation and interpretation components be grounded in the nature of the cognitive model of the domain.  
- James [-@jamesAssessmentLearning2008] highlights important connections between assessment practices and learning theory, noting that both behaviourism and cognitivism emphasize the acquisition of knowledge as a sort of commodity and thus both lead to assessment strategies that emphasize the individual reproduction of knowlege that has either been taught, or has been constructed in meaning-making exercises. Contrary to these approaches, socio-cultural learning theory emphasizes the communal production of meaning through social tools and social interactions between peers and more capable 'others'. Thus, assessment in socio-cultural contexts, while under-theorized, as James argues, ought to be holistic and situated within the communal learning process, rather than an event that happens sometime after the learning has happened.  

-
-  

### Modern Conceptions of Assessment {-}

#### Section Abstract{-}

> The literature shows a change in focus from previous models of assessment to show that assessment is a complex undertaking influenced by instructors' past experiences with assessment, as well as institutional and jurisdictional policies

- Brown [-@brownTeachersConceptionsAssessment2004] showed in a study of K12 teachers in New Zealand that teachers' "conceptions of assessment" (p. 302), or the organizing frameworks teachers use to understand the phenomenon of assessment, are not simple constructs, but are complex and interconnected. Brown's model shows four common conceptions of assessment among K12 teachers:
  - improvement of teaching and learning,
  - school accountability,
  - student accountability, or
  - treating assessment as irrelevant.
- Fletcher et al. [-@fletcherFacultyStudentsConceptions2012] used Brown's [-@brownTeachersConceptionsAssessment2006; -@brownTeachersConceptionsAssessment2004] abridged *Conceptions of Assessment* (CoA) questionnaire to measure learners' and instructors' conceptions of assessment. They report that instructors were more likely than learners to view assessment as consistent and trustworthy methods to understand and improve learning and that learners were more likely to have negative views of assessment and viewed it as a measure of student and institutional accountability.  
- [@lipnevichWhatGradesMean2020] argues that instructor assessment practices are influenced by the practices they experienced as learners
- [@brownQueenslandTeachersConceptions2011] mention that practices are influenced by institutional policies and the social dynamics in their department.
- Earl [-@earlAssessmentLearningUsing2013] distinguished between three conceptions of assessment, as follows: assessment *of* learning (summative assessment), assessment *for* learning (formative assessment by way of feedback), and assessment *as* learning (a subset of assessment *for* learning in which learners employ metacognitive skills to regulate their own learning tasks).  
- DeLuca et al. [-@delucaEstablishingFoundationValid2013] argue that there are four categories of conceptions exhibited by K12 preservice teachers: assessment as testing, assessment as format, assessment purpose, and assessment as process. These conceptions are seen as increasingly complex, with those who see assessment as testing believing that assessment is primarily concerned with summative assessment of learning, usually using teacher-created selected-response tests. Those who see assessment as format tend to focus on whether the assessment is a "performance, product, or objectively-scored assessment" (p. 110). Assessment as purpose is delineated according to the summative/formative binary or Earl's [-@earlAssessmentLearningUsing2013] assessment *of/for/as* learning model. Lastly, assessment as process is based on the National Research Council's description of assessment being a process of reasoning from evidence [-@pellegrinoKnowingWhatStudents2001].  
- Massey et al. [-@masseyAssessmentLiteracyCollege2020] used DeLuca et al.'s [-@delucaEstablishingFoundationValid2013] framework of conceptions in their study of HE instructors' conceptions of assessment before and after an instructional development course focussed on assessment. They also considered the idea that there are two general orientations towards assessment in HE, an "assessment culture" and a "testing culture" [@birenbaumAssessment2000Pluralistic1996; @birenbaumNewInsightsLearning2003, as cited in @masseyAssessmentLiteracyCollege2020]. They report that they saw significant shifts in participants' conceptions of assessment from more simplistic views of assessment as testing pre-treatment, to more complex and nuanced views of assessment as process post-treatment.  
- DeLuca et al. also identify other purposes of assessment such as accountability, gatekeeping, and teacher evaluation.

## Assessment Literacy {-}

#### Section Abstract{-}

> Since 2010, there has been significant focus in the literature on the idea of assessment literacies, indicating a further evolution of research findings towards building models which account for increasing variety of factors influencing instructors. Assessment is seen as a set of skills, beliefs, and context-dependent practices.

- The idea of assessment literacy is relatively recent in the K12 literature and is nascent and under-theorized with respect to HE contexts [@medlandExaminingAssessmentLiteracy2015]. Assessment literacy has been defined variously as "the skills and knowledge teachers require to measure and support student learning through assessment" [@delucaApproachesClassroomAssessment2016],  "a basic understanding of educational assessment and related skills to apply such knowledge to various measures of student achievement" [@xuTeacherAssessmentLiteracy2016], "an individual’s understandings of the fundamental assessment concepts and procedures deemed likely to influence educational decisions" [@pophamAssessmentLiteracyOverlooked2011] and "a dynamic context-dependent social practice that involves teachers articulating and negotiating classroom and cultural knowledges with one another and with learners, in the initiation, development and practice of assessment to achieve the learning goals of students" [@willisConceptualisingTeachersAssessment2013]. Key to these definitions are the ideas that assessment literacy is a complex, multi-faceted construct, that assessment literacy requires *adequate* (not high) levels of psychometric or statistical analyses, and that it is intended to enable learner success.  
- conceptualizations of assessment literacy have tended to be based on sets of standards to which K12 teachers are obligated. The first set of standards was the *Standards for Teacher Competence in Educational Assessment of Students*  (the *Standards*), published by a committee of representatives from the American Federation of Teachers, the National Council on Measurement in Education, and the National Education Association [@StandardsTeacherCompetence1990].  
- Shortly after the publication of the *Standards*, the term *assessment literacy* appeared in the literature with Stiggins' [-@stigginsAssessmentLiteracy1991] article called *Assessment Literacy*. Stiggins initial article was an account of his observation that teacher education programs at the time spent very little time training teachers in the methods and dispositions of educational measurement.
-Stiggins followed this with another article [@stigginsAssessmentLiteracy21st1995] where he outlined five characteristics of sound assessments  
- At around the same time, a group of Canadian educators published the *Principles for Fair Student Assessment Practices for Education in Canada*, Part A of which was a list of 37 guidelines related to five principles of fair student classroom assessment and was based on the 1990 *Standards*  
- Twenty years following the publication of the *Standards*, Brookhart [-@brookhartEducationalAssessmentKnowledge2011] argued that the *Standards* had become outdated because they did not address either the growing practices and ideas of formative assessment (assessment *for* and *as* learning) or standards-based assessment and that they needed to be revised. Brookhart suggested a list of 11 skills (see Appendix A) to adjust the focus of the 1990 *Standards* to be in greater alignment with more modern conceptions of assessment.  
- Finally, in 2015, the Joint Committee on Standards for Educational Evaluation (JCSEE), with key representatives from both Canada and the USA, published the most recent set of standards, called the *Classroom Assessment Standards for PreK12 Teachers* (see Appendix A). The JCSEE standards are grouped into three broad domains (foundations, use, and quality), each with five or six related standards. Despite the similarities to the *Principles for Fair Student Assessment Practices for Education in Canada*, including at least one common committee member, the JCSEE Standards are specifically not intended for use in HE.  
- As traditional conceptions of assessment and the standards expected of teachers, grounded in behaviourism and the need for objectivity tended to focus on assessment as a set of skill-based competencies to be employed by instructors, so assessment literacy could be defined as a set of sequential tasks in which instructors should engage to ensure objectivity and fairness (e.g. [@natrielloImpactEvaluationProcesses1987]). Recently, as curriculum and pedagogy have changed, several researchers have proposed models related to assessment literacy grounded in socio-constructivist views of learning  [@delucaPreparingTeachersAge2012; @pastoreTeacherAssessmentLiteracy2019; @xuTeacherAssessmentLiteracy2016].  

## Approaches to Assessment {-}

#### Section Abstract{-}

> The literature on assessment in more recent years, since 2016, has begun to focus on the idea of 'approaches to assessment', indicating a shift away from the idea of skill-based literacies which may imply that there are 'correct' and 'incorrect' ways to assess learning. DeLuca's model, Approaches to Classroom Assessment, outlines four themes of assessment:
>
> 1. Assessment purposes
> 2. Assessment process
> 3. Assessment fairness
> 4. Assessment theory

- Recently, as curriculum and pedagogy have changed, several researchers have proposed models related to assessment literacy grounded in socio-constructivist views of learning  [@delucaPreparingTeachersAge2012; @pastoreTeacherAssessmentLiteracy2019; @xuTeacherAssessmentLiteracy2016].  
- DeLuca's [-@delucaPreparingTeachersAge2012] model, developed in the context of the *No Child Left Behind* accountability mandate in K12 schools in the USA, is a coherent lens through which to understand how a pre-service teacher could develop assessment expertise throughout their teacher education program. DeLuca framed assessment literacy within Fostaty Young and Wilson's [-@fostatyyoungAssessmentLearningICE2000] ICE model which presents an integrated progression of learning through three levels of complexity, ideas, connections, and extensions.  
- Willis et al. [-@willisConceptualisingTeachersAssessment2013] describe assessment literacy in alignment with Bernstien's [-@bernsteinVerticalHorizontalDiscourse1999] idea that there are "horizontal" and "vertical" discourses (p. 159) with respect to assessment.  
- Similarly, Xu and Brown's [-@xuTeacherAssessmentLiteracy2016] model, teacher assessment literacy in practise (TALiP) presents a pathway for pre-service teachers to gain expertise in assessment.  
- Finally, Pastore and Andrade [-@pastoreTeacherAssessmentLiteracy2019] developed their model through a Delphi inquiry of 35 international experts in educational assessment and teacher education. They propose a model with three dimensions, conceptual, praxeological, and socio-emotional.  
- The authors of each of these three models recognize that assessment literacy is conceptualized as a multi-dimensional construct encompassing psychometric skills, affective beliefs and values, external and regulatory environments, and socially negotiated practices. However, these models are largely specific to the K12 environment in general, and more specifically related to the preparation of K12 teachers.  
- Bearman et al. [-@bearmanSupportAssessmentPractice2016] proposed a model for assessment decision-making in Australian HE, the Assessment Design Decisions Framwork (ADDF) in which the authors acknowledge the difficulty in translating idealized beliefs about assessment into actual practice as well as the lack of literature regarding *how* HE instructors go about designing assessments.

## Assessment and Measurement  {-}

#### Section Abstract {-}

> Regardless of a particular instructor's approach to assessment it is critical that the inferences drawn from the evidence provided are valid, reliable, and fair. The validity of an inference is the degree to which the inference is supported by the evidence for a particular use of the scores [@aeraStandardsEducationalPsychological2014]. Reliability refers to the consistency of the measure. Fairness is a social concept related to bias, which is any construct-irrelevant source of variance that results in systematically higher or lower scores for particular groups (Bulut, 'EDPY507 Course Materials', 2020)

### Validity {-}

### Reliability  {-}

### Fairness {-}

## Assessment in Higher Education  {-}

#### Section Abstract {-}

> The preponderance of the literature on assessment is published in the context of K12 schooling, and there is comparitively less published specific to higher education. The higher education context differs from K12 in significant ways, including instructors having greater freedom and autonomy in how they approach assessment in their courses and also in that higher education instructors generally do not have access to formal academic preparation for teaching or assessment. This tends to lead to both a wide variety of approaches to assessment and also a widespread reliance on instructors approaching assessment in the same way their instructors approached assessment.

## Impact of Technology on Assessment in Higher Education  {-}

> The literature shows that technology is ubiquitous in higher education and has had significant impacts, with both instructors and learners creating digital documents and other artifacts. However, the literature also shows that technology has been slower to impact the kinds of assessments that instructors use in their classes.

[@broadfootAssessmentTwentyFirstCenturyLearning2016]