# Assessment and Digital Technology in Higher Education: A Review of the Literature {-}

## Abstract {-}

Assessment is a core component of teaching and learning in higher education which has been impacted in various ways by the growth of technology in society and education. While technology is often employed in society to increase efficiency, this may not be a helpful goal or metric when applying technology to the process of assessing learning. This review of the literature explores how technology has impacted assessment practices in higher education and how faculty, instructors, and educational technologists encourage ethical approaches to using technology for assessment. 

## Proposal {-}

Higher education has been significantly impacted by the advent and growth of digital technologies. Student Information Systems (SIS), such as Banner or Jenzabar, have created efficiencies in how learners are registered in programs and courses, how learners plan their programs, and how administrators create timetables and schedules. Learning Management Systems (LMS), such as Moodle, Blackboard, Canvas, and Desire2Learn, have created efficiencies in connecting SISs with front-line staff and faculty by automating the process of ensuring that learners show up in the proper section of a given course, giving faculty and instructors relatively robust tools for communicating with learners, and distributing and gathering documents. Data analysis platforms such as Tableau and R have created efficiencies in how universities analyze learner behaviour in courses [@watsonSmallDataOnline2017]. Customer Relationship Management (CRM) software such as Salesforce have created efficiencies in how universities connect with alumni, manage donor relations, and recruit new learners. In each of these cases, increases in efficiency have been the point, or the end goal of the implementation of technology. Efficiency has amplified the impact of peoples' work and is virtuous if your goal is profitability.

However, if your goal is the betterment of human beings, doing the same things more efficiently may be counter-productive, and it may be preferrable to instead do different things [@pellegrinoPerspectivesIntegrationTechnology2010; @oldfieldAssessmentDigitalAge2012]. The tri-partite goals of the modern university: research, teaching, and service, have traditionally had as their end goal the betterment of society and the individuals within. Teaching and learning are profoundly inefficient tasks subject to myriad influences and personal characteristics of both the teacher and the learner. As a key component of the teaching and learning process, assessment is also subject to many influences, making efficiencies detrimental to the process.

This presentation will be a summary of a literature review conducted to explore current research on the impact of technology on assessment in higher education. A preliminary review shows that there are multiple ways that technology has impacted assessment practices in higher education. First, Large Scale Assessments (LSA) used as entrance exams to university (Scholastic Aptitude Test), or to specific programs (Law School Admissions Test, Medical College Admission Test), have benefitted from the use of digital data analysis tools to improve validity and reliability and also from advances in automated item generation. Assessments used for admission into specific professions, such as the National Council Licensure Examination (NCLEX) for those wishing to enter the nursing profession after completing a degree in Nursing utilize computerized adaptive testing [@smithglasgowStandardizedTestingNursing2019] where the difficulty of questions the candidate sees is determined by their previous performance. Second, instructors are using digital tools to revise their assessment practices to align with curricular goals of collaboration, problem-solving, creativity, and divergent thinking [@broadfootAssessmentTwentyFirstCenturyLearning2016]. Third, some instructors and institutions are using technology to allow for remote exam candidates to write exams in proctored environments [@selwynNecessaryEvilRise2021]. Finally, instructors are using technology to enhance and also to capture evidence of learner interactions in remote, asynchronous learning environments [@pellegrinoPerspectivesIntegrationTechnology2010]. Each of these uses will be explored in relation to one of the foundational goals of higher education, the betterment of individuals for the good of society.


## Statement of Engagement {-}

Participants will be given the opportunity in small groups to discuss how they might apply the findings of the literature review to their own teaching or research practice, followed by a short debrief with the full group.