# Approaches to Classroom Assessment Inventory - Higher Education {-}

The ACAI is part of an educational research project. By completing the ACAI you will be consenting to your anonymous responses being including in our research study. Additional details on research ethics are presented in this letter of information and consent page.

**Project title:** Teachers’ Approaches to Classroom Assessment

**Ethical clearance:** This study has been granted clearance according to the recommended principles of Canadian ethics guidelines and Queen’s policies.

**Purpose:** The purpose of this research is to develop and test a survey to examine teachers’ approaches to classroom assessment. Results from this survey will serve to describe teachers’ assessment practices within various educational systems. Findings from this study will provide a basis for future teacher professional development activities in assessment.

**Participation:** If you agree to participate, you will be asked to complete the online survey. In total, completion of the survey should take approximately 20 minutes. The survey includes questions about your approach to assessment practice, your perceived skill in assessment, and professional learning interests in assessment. At the end of the survey you will be asked if you are interested in participating in future research on assessment. This question is optional, and you may choose not to answer it. However, if you are interested, you will be asked for your name and contact information.

**Withdrawal Procedures:** There are no known risks to participating in this study. Participation is voluntary and you are free to withdraw at any time by simply closing your browser window. However, once you have submitted your responses, you will be unable to withdraw your data from the study. If you have elected to provide your contact information at the end of the survey, you may request removal of your data. In order to withdraw, please contact the principal researcher, Christopher DeLuca, via email (cdeluca@queensu.ca) or phone (613-533-6000 x.77675).

**Privacy:** Your confidentiality will be maintained to the extent possible. Presentation or publication of research results will not identify you in any way. Your name will not be used in the publication or presentation of results. All of the data will be stored on password-protected computers at Queen’s University and, in accordance with Queen’s policies, will be retained for at least five years before being destroyed. Contact information, should you choose to provide it, will be stored separately from your survey responses. Only the researcher and research assistants will have access to the data. The survey data obtained in this research will be encrypted using SSL and stored on secure servers located in Canada and your IP address will not be known or identifiable.

**Consent & Agreeing to Participate:** If you are interested in participating in this study, please click on the NEXT button below to complete the survey. By completing the survey you freely agree to participate in this study.
Questions: Any questions about study participation may be directed to Dr. Christopher DeLuca (613 533 6000 x77675 or by email at cdeluca@queensu.ca). Any ethical concerns about the study may be directed to the Chair of the General Research Ethics Board at 613-533-6081 or chair.GREB@queensu.ca.

Do you consent?
  Yes No

## Part A {-}

### Scenario 1: Large Class Feedback {-}

> You are teaching a large enrollment course. The students will be submitting bi-weekly assignments, a midterm exam, and a culminating assignment all designed to support their learning. 

| Dimension | Priority Approach | Description of Priority Approach |
| --- | --- | --- |
| Assessment Purpose | Assessment of Learning | Grade each bi-weekly assignment. |
|   | Assessment for learning | Read a subset of bi-weekly assignments, identify and share performance trends with the whole class. |
|   | Assessment as learning | Ask students to self-assess their bi-weekly assignments using evaluative criteria. |
| Assessment Process | Design | Use performance trends from the bi-weekly assignments to inform the redesign of the midterm or culminating. |
|   | Scoring | Develop a rubric or scoring guide to assess the culminating assignment in advance of student submissions. |
|   | Communication | Dedicate class time to discuss students’ performance trends from the midterm and address gaps in learning so students are better prepared for the culminating assignment. |
| Fairness | Standard Treatment | Have every student complete the same culminating assignment using the same scoring rubric or guide.  |
|   | Equitable Approach | Have all students complete the same culminating assignment with formal accommodations for students who require them. |
|   | Personalized Approach | Provide students with a choice of three different culminating assignments that assess the same learning goals. |
| Assessment Theory | Consistent | Consistently apply late submission policies for all students when generating grades.  |
|   | Contextual | Consider each student’s individual circumstances when deciding how to apply late submission policies. | 
|   | Balanced | Use the late submission policy as a guideline to ensure a consistent principle is applied while also using professional judgement for students with individual circumstances.|

### Scenario 2: Online Group Work {-}

>A core assignment in your course involves students working in groups online. 

| Dimension | Priority Approach | Description of Priority Approach |
| --- | --- | --- |
| Assessment Purpose | Assessment of Learning | Grade the assignment solely based on the group’s final product. |
|   | Assessment for learning | Engage students in an ongoing peer feedback process to enhance group collaboration. |
|   | Assessment as learning | Engage students in self-assessment to increase their accountability and engagement in the assignment. |
| Assessment Process | Design | Leverage online design features to engage students in peer feedback and self- assessment.   |
|   | Scoring | Take group member feedback into consideration when generating final grades. |
|   | Communication | Communicate grading decisions based on evaluation criteria and evidence of student learning. |
| Fairness | Standard Treatment | Give all group members the same grade.  |
|   | Equitable Approach | Monitor barriers to a student’s performance in group work (e.g., language, technology) and grade accordingly.  |
|   | Personalized Approach | Grade each student individually based on their contribution to the group’s process and product. |
| Assessment Theory | Consistent | Use the same rubric to consistently grade all groups’ assignments.  |
|   | Contextual | Modify and apply the rubric differently in response to unexpected group events (e.g., group member leaves). | 
|   | Balanced | Use the same rubric, but consider group composition, size, and cohesion when grading. |

### Scenario 3: Orientations to Assessment/Grading {-}

> There are expectations in your department that grades should be distributed across the grading scale. However, your class averages are consistently lower than your colleagues’. Your course assessment scheme includes two term exams and one final exam.

| Dimension | Priority Approach | Description of Priority Approach |
| --- | --- | --- |
| Assessment Purpose | Assessment of Learning | Provide students with additional graded assessments to chunk learning into smaller units.  |
|   | Assessment for learning | Provide students with additional opportunities to check their understanding throughout the course (e.g., ungraded quizzes, exit slips). |
|   | Assessment as learning | Provide self-assessment opportunities to help students recognize and address gaps in their learning.  |
| Assessment Process | Design | Analyze exam results to determine if weak performance was due to exam design issues.   |
|   | Scoring | Remove exam questions that most students struggled with and re-calculate student scores. |
|   | Communication | Schedule class time to review exam performance to address learning gaps. |
| Fairness | Standard Treatment | Shift all exam grades up so averages are consistent with departmental colleagues’.   |
|   | Equitable Approach | Provide students who performed below the class average with the opportunity to rewrite an equivalent exam.  |
|   | Personalized Approach | Grade each student individually based on their contribution to the group’s process and product. |
| Assessment Theory | Consistent | Analyze the consistency of student performance across course exams.   |
|   | Contextual | Analyze exam questions to ensure alignment with taught content. | 
|   | Balanced | Analyze how students performed on exams in relation to taught content.  |

### Scenario 4: Multiple Sections of a Course {-}

> You teach a course with multiple sections taught by various instructors. Your students have complained to you that assignments are constructed and graded differently across sections.

| Dimension | Priority Approach | Description of Priority Approach |
| --- | --- | --- |
| Assessment Purpose | Assessment of Learning | Explain to students that while learning outcomes are the same across sections, grades are based on their individual performance on assignments.  |
|   | Assessment for learning | Ensure students have the opportunity to receive feedback prior to submitting assignments to increase their focus on learning over grades. |
|   | Assessment as learning | Invite students to reflect on their personal learning goals for the course so they can plan for their own success in your course.  |
| Assessment Process | Design | Engage in a collaborative design process with other instructors to set standards and design common assignments.  |
|   | Scoring | Collaboratively score a subset of assignments with the other instructors to ensure consistent use of scoring guides across sections. |
|   | Communication | Communicate your grading approach to your students and explain how it aligns with intended learning goals. |
| Fairness | Standard Treatment | Propose a standard approach to assignments and grading be applied across all sections.   |
|   | Equitable Approach | Assure students that while the assignments may be different across the sections, they assess the same learning outcomes.  |
|   | Personalized Approach | Offer students the opportunity to select and complete an assignment from another section. |
| Assessment Theory | Consistent | Work with the other instructors to revise all assignments across sections so they are all the same.  |
|   | Contextual | Justify differences in approaches to assessment based on instructor orientations to assessment, teaching context, and students’ learning needs. | 
|   | Balanced | Recognize student concerns and engage in practices that ensure your assignments are equivalent to those in other sections.  |

### Scenario 5: Academic Integrity

> You discover that a student has plagiarized some of their assignment (e.g., an essay, lab report).

| Dimension | Priority Approach | Description of Priority Approach |
| --- | --- | --- |
| Assessment Purpose | Assessment of Learning | Give the student a 0 on the assignment.  |
|   | Assessment for learning | Have the student re-write the plagiarized section in their own words, then re-grade the assignment. |
|   | Assessment as learning | Ask the students to reflect on why plagiarism is a problem and what they would do differently next time.  |
| Assessment Process | Design | As the instructor, reflect on how the assignment could have been structured differently to deter plagiarism.  |
|   | Scoring | Adjust the student’s grade to reflect the portion of work that was plagiarized.  |
|   | Communication | Discuss with the student the reasons for the plagiarism, severity of plagiarism, and negotiate potential next steps for their learning. |
| Fairness | Standard Treatment | Apply the same consequence you would for other students to ensure all students are treated the same.  |
|   | Equitable Approach | Consider if the student has identified accommodations before determining response to plagiarism.  |
|   | Personalized Approach | Discuss why the student plagiarized and agree upon an appropriate alternative assignment. |
| Assessment Theory | Consistent | Apply all aspects of institutional policy on academic integrity to ensure consistency across all students.  |
|   | Contextual | Consider the original aspects of the assignment and the plagiarized text to determine what the student knows and does not appear to know related to learning outcomes. | 
|   | Balanced | Consider extenuating circumstances surrounding the plagiarism and use professional judgement when applying the institutional academic integrity policy.  |

## Part B {-}

Questions about assessment practices and professional learning

Below are a number of statements about assessment. Please indicate your level of agreement with each statement (1=strongly disagree; 2=disagree; 3=somewhat disagree; 4=somewhat agree; 5=agree; 6=strongly agree). There are no right or wrong answers. We are interested in your honest opinions about assessment. If you do not understand the statement, select 'Don't Know.'

|   | Strongly Disagree - 1 | 2 | 3 | 4 | 5 | Strongly Agree - 6 | Don't Know |
|---| --- | ---|---| --- | ---|---| --- | 
| The primary purpose of assessment is to assign a grade to student work. |  |  |  |  |  |   |   |
| Assessment should be used to determine if students have met program standards. |  |  |  |  |  |   |   |
| Feedback from assessment improves student learning. |  |  |  |  |  |   |   |
| By using assessment, instructors can track the progress of students. |  |  |  |  |  |   |   |
| Students should use assessment to evaluate their own work. |  |  |  |  |  |   |   |
| Students are able to provide accurate and useful feedback to each other. |  |  |  |  |  |   |   |
| Instructors have the skills and knowledge to construct good assessments. |  |  |  |  |  |   |   |
| For good assessment, instructors need extensive knowledge of the subject matter. |  |  |  |  |  |   |   |
| Assessment involves judging a student’s performance in relation to a set of goals/standards/criteria. |  |  |  |  |  |   |   |
| The results of assessment should inform future teaching. |  |  |  |  |  |   |   |
| Assessment results should be used to provide evidence of student progress for administrative purposes. |  |  |  |  |  |   |   |
| Assessment is useful when reporting a student's achievement/progress to department heads and administration.  |  |  |  |  |  |   |   |
| An important component of assessment is preparing students for large-scale tests (e.g., certification, licensing, MCAT, LSAT, GRE). |  |  |  |  |  |   |   |
| All students should achieve a minimum score on a standardized entrance exam as part of admission to higher education. |  |  |  |  |  |   |   |
| All assessments should be adapted for students with identified accommodation needs. |  |  |  |  |  |   |   |
| Students with exceptionalities should be provided with different assessments than other students. |  |  |  |  |  |   |   |
| Instructors should offer choice in their assessments based on students’ learning needs. |  |  |  |  |  |   |   |
| Assessment helps instructors identify individual students’ learning needs. |  |  |  |  |  |   |   |
| Assessment results provide reliable information. |  |  |  |  |  |   |   |
| Assessment involves instructors making judgements about how well a student is learning in relation to other students. |  |  |  |  |  |   |   |
| Assessment results are a good indicator of the quality of a program.  |  |  |  |  |  |   |   |
| Assessment results reflect the quality of teaching. |  |  |  |  |  |   |   |
| Assessment is an imprecise process. |  |  |  |  |  |   |   |
| Observing students is a valid form of assessment. |  |  |  |  |  |   |   |
| Assessment is of little use to instructors on a day-to-day basis. |  |  |  |  |  |   |   |
| Assessment interrupts students’ learning. |  |  |  |  |  |   |   |
| Assessment is a stressful activity for students. |  |  |  |  |  |   |   |
| Assessment takes time away from teaching. |  |  |  |  |  |   |   |
| Instructors use too many assessments. |  |  |  |  |  |   |   |
| Assessment is a positive force for improving classroom culture. |  |  |  |  |  |   |   |
| Assessments motivate students to do their best. |  |  |  |  |  |   |   |
| Assessment is a positive experience for students. |  |  |  |  |  |   |   |

In 2-3 sentences, explain your approach to assessment to your students. 